language: python
python:
  - "3.6"
  - "3.7"

env:
  - ANSIBLE_VERSION=2.8.6
  - ANSIBLE_VERSION=2.9.0
  - ANSIBLE_VERSION=2.9.5

branches:
  only:
    - master

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y graphviz
  - pip install -U pip setuptools wheel

install:
  - pip install -qUr tests/requirements_tests.txt
  - pip install -q ansible==$ANSIBLE_VERSION
  - pip freeze

script:
  - make test
  - make test_install ANSIBLE_VERSION=$ANSIBLE_VERSION

after_success:
  - pip install -U coveralls
  - coveralls
