---
title: Ansible Playbook Grapher
---
%%{ init: { "flowchart": { "curve": "bumpX" } } }%%
flowchart LR
	%% Start of the playbook '../playground/site.yml'
	playbook_83cbb62d("../playground/site.yml")
		%% Start of the play 'Play: webserver (1)'
		play_82c80f91["Play: webserver (1)"]
		style play_82c80f91 fill:#a52732,color:#ffffff
		playbook_83cbb62d --> |"1"| play_82c80f91
		linkStyle 0 stroke:#a52732,color:#a52732
			%% Start of the role 'webserver'
			play_82c80f91 --> |"1"| role_2239c29d
			linkStyle 1 stroke:#a52732,color:#a52732
			role_2239c29d("[role] webserver")
			style role_2239c29d fill:#a52732,color:#ffffff,stroke:#a52732
				task_fb454094[" loadbalancer : Debug vars"]
				style task_fb454094 stroke:#a52732,fill:#ffffff
				role_2239c29d --> |"1"| task_fb454094
				linkStyle 2 stroke:#a52732,color:#a52732
				task_434f4cbd[" webserver : Debug vars"]
				style task_434f4cbd stroke:#a52732,fill:#ffffff
				role_2239c29d --> |"2 [when: hostvar01]"| task_434f4cbd
				linkStyle 3 stroke:#a52732,color:#a52732
				task_2a891b19[" webserver : Debug some more"]
				style task_2a891b19 stroke:#a52732,fill:#ffffff
				role_2239c29d --> |"3"| task_2a891b19
				linkStyle 4 stroke:#a52732,color:#a52732
				task_8b6e8d70[" webserver : Create html from template.j2"]
				style task_8b6e8d70 stroke:#a52732,fill:#ffffff
				role_2239c29d --> |"4"| task_8b6e8d70
				linkStyle 5 stroke:#a52732,color:#a52732
				task_9eb1e98b[" webserver : Included task"]
				style task_9eb1e98b stroke:#a52732,fill:#ffffff
				role_2239c29d --> |"5"| task_9eb1e98b
				linkStyle 6 stroke:#a52732,color:#a52732
			%% End of the role 'webserver'
			%% Start of the block 'Block'
			block_790e88fa["[block] Block"]
			style block_790e88fa fill:#a52732,color:#ffffff,stroke:#a52732
			play_82c80f91 --> |"2"| block_790e88fa
			linkStyle 7 stroke:#a52732,color:#a52732
			subgraph subgraph_block_790e88fa["Block "]
				task_4f93bb22[" Debug var"]
				style task_4f93bb22 stroke:#a52732,fill:#ffffff
				block_790e88fa --> |"1"| task_4f93bb22
				linkStyle 8 stroke:#a52732,color:#a52732
			end
			%% End of the block 'Block'
		%% End of the play 'Play: webserver (1)'
		%% Start of the play 'Play: database (2)'
		play_d7e3e522["Play: database (2)"]
		style play_d7e3e522 fill:#a40cc0,color:#ffffff
		playbook_83cbb62d --> |"2"| play_d7e3e522
		linkStyle 9 stroke:#a40cc0,color:#a40cc0
			%% Start of the role 'database'
			play_d7e3e522 --> |"1"| role_11e0eed8
			linkStyle 10 stroke:#a40cc0,color:#a40cc0
			role_11e0eed8("[role] database")
			style role_11e0eed8 fill:#a40cc0,color:#ffffff,stroke:#a40cc0
				task_12f63bc8[" database : Debug vars"]
				style task_12f63bc8 stroke:#a40cc0,fill:#ffffff
				role_11e0eed8 --> |"1"| task_12f63bc8
				linkStyle 11 stroke:#a40cc0,color:#a40cc0
				task_4a7519bd[" loadbalancer : Debug vars"]
				style task_4a7519bd stroke:#a40cc0,fill:#ffffff
				role_11e0eed8 --> |"2"| task_4a7519bd
				linkStyle 12 stroke:#a40cc0,color:#a40cc0
				task_8b036c98[" database : debug database block"]
				style task_8b036c98 stroke:#a40cc0,fill:#ffffff
				role_11e0eed8 --> |"3"| task_8b036c98
				linkStyle 13 stroke:#a40cc0,color:#a40cc0
			%% End of the role 'database'
		%% End of the play 'Play: database (2)'
		%% Start of the play 'Play: loadbalancer (1)'
		play_fcdd070f["Play: loadbalancer (1)"]
		style play_fcdd070f fill:#b10ac2,color:#ffffff
		playbook_83cbb62d --> |"3"| play_fcdd070f
		linkStyle 14 stroke:#b10ac2,color:#b10ac2
		%% End of the play 'Play: loadbalancer (1)'
	%% End of the playbook '../playground/site.yml'

