---
title: Ansible Playbook Grapher
---
%%{ init: { "flowchart": { "curve": "bumpX" } } }%%
flowchart LR
	%% Start of the playbook '../playground/site.yml'
	playbook_37af12da("../playground/site.yml")
		%% Start of the play 'Play: webserver (1)'
		play_de087867["Play: webserver (1)"]
		style play_de087867 fill:#6c9d2f,color:#ffffff
		playbook_37af12da --> |"1"| play_de087867
		linkStyle 0 stroke:#6c9d2f,color:#6c9d2f
			%% Start of the role 'webserver'
			play_de087867 --> |"1"| role_2239c29d
			linkStyle 1 stroke:#6c9d2f,color:#6c9d2f
			role_2239c29d("[role] webserver")
			style role_2239c29d fill:#6c9d2f,color:#ffffff,stroke:#6c9d2f
				%% Start of the role 'loadbalancer'
				role_2239c29d --> |"1"| role_2e324a8f
				linkStyle 2 stroke:#6c9d2f,color:#000000
				role_2e324a8f("[role] loadbalancer")
				style role_2e324a8f fill:#000000,color:#ffffff,stroke:#000000
				%% End of the role 'loadbalancer'
			%% End of the role 'webserver'
			%% Start of the block 'Block'
			block_8b9ea529["[block] Block"]
			style block_8b9ea529 fill:#6c9d2f,color:#ffffff,stroke:#6c9d2f
			play_de087867 --> |"2"| block_8b9ea529
			linkStyle 3 stroke:#6c9d2f,color:#6c9d2f
			subgraph subgraph_block_8b9ea529["Block "]
				%% Start of the role 'loadbalancer'
				block_8b9ea529 --> |"1"| role_2e324a8f
				linkStyle 4 stroke:#6c9d2f,color:#000000
			end
			%% End of the block 'Block'
		%% End of the play 'Play: webserver (1)'
		%% Start of the play 'Play: database (2)'
		play_7261dc3b["Play: database (2)"]
		style play_7261dc3b fill:#5022aa,color:#ffffff
		playbook_37af12da --> |"2"| play_7261dc3b
		linkStyle 5 stroke:#5022aa,color:#5022aa
			%% Start of the role 'database'
			play_7261dc3b --> |"1"| role_11e0eed8
			linkStyle 6 stroke:#5022aa,color:#5022aa
			role_11e0eed8("[role] database")
			style role_11e0eed8 fill:#5022aa,color:#ffffff,stroke:#5022aa
				%% Start of the role 'loadbalancer'
				role_11e0eed8 --> |"1"| role_2e324a8f
				linkStyle 7 stroke:#5022aa,color:#000000
			%% End of the role 'database'
			%% Start of the role 'loadbalancer'
			play_7261dc3b --> |"2"| role_2e324a8f
			linkStyle 8 stroke:#5022aa,color:#000000
		%% End of the play 'Play: database (2)'
		%% Start of the play 'Play: loadbalancer (1)'
		play_5fdc6338["Play: loadbalancer (1)"]
		style play_5fdc6338 fill:#498363,color:#ffffff
		playbook_37af12da --> |"3"| play_5fdc6338
		linkStyle 9 stroke:#498363,color:#498363
			%% Start of the role 'loadbalancer'
			play_5fdc6338 --> |"1"| role_2e324a8f
			linkStyle 10 stroke:#498363,color:#000000
		%% End of the play 'Play: loadbalancer (1)'
	%% End of the playbook '../playground/site.yml'

